version: '3.8'

services:
  express-server:
    build: .
    ports: 
     - "5000:3000"
    restart: always
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase
      - JWT_SECRET_KEY=JWT_SECRET_KEY
      - Patient_JWT_SECRET_KEY=30d
      - SENDEREMAIL=SENDEREMAIL
      - SENDERPASSWORD=SENDERPASSWORD
      - JWT_LIFETIME=30d
      - Patient_JWT_LIFETIME=30d
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
    name: mongodb_data