version: '3.8'

services:
  express-server:
    build: .
    ports: 
     - "5000:5000"
    restart: always
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongodb:27017/mydatabase
      - JWT_SECRET_KEY=JWT_SECRET_KEY
      - Patient_JWT_SECRET_KEY=30d
      - SENDEREMAIL=SENDEREMAIL
      - SENDERPASSWORD=SENDERPASSWORD
      - JWT_LIFETIME=30d
      - Patient_JWT_LIFETIME=30d
      - apiKey=AIzaSyCWKQhia0I9td5n9p74cXeNpymR-z4LAsc
      - authDomain=bharat-seva-1297a.firebaseapp.com
      - projectId=bharat-seva-1297a
      - storageBucket=bharat-seva-1297a.appspot.com
      - messagingSenderId=1059569736175
      - appId=1:1059569736175:web:333ebb9c3a433f33f1fe1a
      - measurementId=G-FSS43S7B6Kc
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  prometheus:
    image: prom/prometheus:v2.30.3
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - express-server

  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
      - ./grafana/logs:/var/log/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer  
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  mongodb_data:
    name: mongodb_data